name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 0 点自动同步一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: ourongxing/newsnow
          upstream_branch: main
          target_branch: main
          test_mode: false
